server:
  port: 9004
#  应用数据源及数据库连接信息配置
spring:
  application:
    name: pt-admin-api
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bmy?useUnicode=true&characterEncoding=utf-8
      username: root
      password: bmy123!@#
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,wall
  redis:
    host: localhost
    port: 6379
    password:
    database: 3
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 日志打印配置
logging:
  level:
    root:  INFO
    org.springframework:  ERROR
    org.mybatis:  INFO

wx:
  official:
    app_id: wx832ee4c0d71fc260
    app_secret: f92f428a6edd647cb2cbf26530314bcc
    api:
      auth: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
      get_news: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=%s
      get_count: https://api.weixin.qq.com/cgi-bin/material/get_materialcount?access_token=%s

