server:
  port: 9001
spring:
  profiles:
    include: core-prod,dao-prod
  application:
    name: pt-gateway-service
  cloud:
    gateway:
      routes:
        - id: pt-admin-api
          uri: lb://pt-admin-api
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: pt-wx-api
          uri: lb://pt-wx-api
          predicates:
            - Path=/wx/**
          filters:
            - StripPrefix=1
