minio:
  access-key: admin
  secret-key: admin123456
  host: http://node2.bmy8.xyz:8999
server:
  port: 9005
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  application:
    name: pt-file-center
  cloud:
    inetutils:
      ignored-interfaces: eth.*              # 忽略网卡，eth.*，正则表达式
      preferred-networks: ${spring.cloud.nacos.discovery.server-addr}
    nacos:
      discovery:
        server-addr: localhost:8848

